DATA_PATH = '../../../data'
DATASET_PARAMETERS_PREFIX = "dataset"
AGENT_PARAMETERS_PREFIX = "agent"
EVALUATION_POLICY_PARAMETERS_PREFIX = "evaluation_policy"
METRIC_EVALUATOR_PARAMETERS_PREFIX = "metric_evaluator"
METRIC_PARAMETERS_PREFIX = "metric"